// <auto-generated />
namespace SmartKitchen3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class firstOneAfterMerge : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(firstOneAfterMerge));
        
        string IMigrationMetadata.Id
        {
            get { return "201910181118559_firstOneAfterMerge"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
